server:
  port: 8082

eureka:
  client.service-url:
    defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${server.port}}
    prefer-ip-address: true
    appname: order
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/article?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  application:
    name: order

mybatis:
  mapper-locations: classpath:*.xml
  type-aliases-package: root.entity